#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

# Try to parse the stdin as JSON.
# If parsing fails, output everything to stderr
data = json.load(sys.stdin)

# agent.set_env("CREATE_MYSQL_USER", data["create_mysql_user"])
agent.set_env("MYSQL_USER_NAME", data.get("mysql_user_name",''))
agent.set_env("MYSQL_USER_DB", data.get("mysql_user_db",''))
password = {"MYSQL_ADMIN_PASS":data["mysql_admin_pass"],"MYSQL_USER_PASS": data.get("mysql_user_pass",'')}
agent.write_envfile("password.env", password)

agent.set_env("CREATE_MYSQL_USER", data.get("create_mysql_user",False))
agent.set_env("PHP_UPLOAD_MAX_FILESIZE", data.get("php_upload_max_filesize",'100') + 'M')
agent.set_env("PHP_POST_MAX_SIZE", data.get("php_upload_max_filesize",'100') + 'M')
agent.set_env("PHP_MEMORY_LIMIT", data.get("php_memory_limit",'512') + 'M')
agent.set_env("PHPMYADMIN_ENABLED", data.get("phpmyadmin_enabled",True))

# Bind the new domain, overriding previous values (unbind)
agent.bind_user_domains([os.environ.get('LAMP_LDAP_DOMAIN','')])