#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["host"] = os.getenv("TRAEFIK_HOST","")
config["http2https"] = os.getenv("TRAEFIK_HTTP2HTTPS") == "True"
config["lets_encrypt"] = os.getenv("TRAEFIK_LETS_ENCRYPT") == "True"
config["mysql_user_name"] = os.getenv("MYSQL_USER_NAME","")
config["mysql_user_db"] = os.getenv("MYSQL_USER_DB","")

# check if the mysql is configured
config['firstConfig'] = True if not os.path.exists("password.env") else False

config["mysql_admin_pass"] = agent.read_envfile("password.env")["MYSQL_ADMIN_PASS"] if os.path.exists("password.env") else "Nethesis,1234"
config["mysql_user_pass"] = agent.read_envfile("password.env")["MYSQL_USER_PASS"] if os.path.exists("password.env") else "Nethesis,1234"

config["create_mysql_user"] = os.getenv("CREATE_MYSQL_USER","False") == "True"
config["php_upload_max_filesize"] = os.getenv("PHP_UPLOAD_MAX_FILESIZE","100").removesuffix('M')
config['php_memory_limit'] = os.getenv("PHP_MEMORY_LIMIT","512").removesuffix('M')
config["phpmyadmin_enabled"] = os.getenv("PHPMYADMIN_ENABLED","True") == "True"

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
